### ISSUE TITLE
AttributeError: module 'ssl' has no attribute 'wrap_socket'

### ISSUE THREAD

**Issue by glimchb** [DMTF/Redfish-Mockup-Server#103]
```
| Serving Mockup in absolute path: /usr/src/app/public-rackmount1
| Using SSL with certfile: /opt/cert.pem
| Traceback (most recent call last):
|   File "/usr/src/app/redfishMockupServer.py", line 918, in <module>
|     main()
|   File "/usr/src/app/redfishMockupServer.py", line 867, in main
|     myServer.socket = ssl.wrap_socket(myServer.socket, certfile=sslCert, keyfile=sslKey, server_side=True)
|                       ^^^^^^^^^^^^^^^
| AttributeError: module 'ssl' has no attribute 'wrap_socket'
 with code 1
```

proposed fix #104

**Comment by texroemer** [comment]
Hi @glimchb 

FYI i'll be posting Redfish mockup client examples in a few days which can be leveraged using Redfish mockup server. I haven't posted these yet because i'm currently waiting on Dell documentation to get approved and posted. This document will help the user with running the Redfish mockup server and walking you through running multiple Redfish workflow examples. 

Thanks
Tex

**Comment by glimchb** [comment]
> FYI i'll be posting Redfish mockup client examples in a few days which can be leveraged using Redfish mockup server. I haven't posted these yet because i'm currently waiting on Dell documentation to get approved and posted. This document will help the user with running the Redfish mockup server and walking you through running multiple Redfish workflow examples.

thanks @texroemer that would be great, while not sure how this is relevant with the fix for SSL deprecation of the method in this issue...
