### ISSUE TITLE
Missing ETag support in AccountService

### ISSUE THREAD

**Issue by MoshiBin** [DMTF/Redfish-Mockup-Server#79]
Real server returns an ETag for accounts, and later expects the current ETag in PATCH request headers. The mock server does not return such a header at all.

```python
>>> real_resp = real_server.get("/redfish/v1/AccountService/Accounts/0")
>>> print(real_resp.getheader("ETag"))
W/"F42F8DCB"

>>> mock_resp = mock.server.get("/redfish/v1/AccountService/Accounts/0")
>>> print(mock_resp.getheader("ETag"))
None
```

**Comment by mraineri** [comment]
Is there a particular reason we need this in the mockup server? Usually when we start getting to this level of detail, it's better suited for the Redfish Interface Emulator, which is really a "more functional" mockup than this tool.

**Comment by mraineri** [comment]
The other thing that's used today for headers in general is when you capture a mockup, you can specify the `-H` argument, which will capture HTTP headers for each resource in `headers.json`. If this file is present in the mockup, the mockup server will send those headers back as is.

**Comment by mraineri** [comment]
Discussion from the call: The group thinks active ETag management is better suited for the Interface Emulator, or using the existing `-H` option to leverage the headers captured from the service. The scope of this tool is to allow a client to perform simple GETs on resources in order to view sets of data.
